config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'
  root 'stays#index'
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  devise_scope :user do
    get 'signin' => 'devise_token_auth/sessions#new'
    post 'signin' => 'devise_token_auth/sessions#create'
    post 'signup' => 'users#create'
    get "users/show" => "users#show"
  end
  resources :users , only: [:edit,:update]
  
  get "stays/insear" => "stays#insear"
  get "stays/index" => "stays#index"
  
  
  resources :reservations
  
  delete 'reservations/:id' => 'reservations#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :reservations, only:[:index, :new, :create, :destroy] do
    collection do
      post :confirm
    end
  end

  

  resources :stays, only: [:index, :new, :create, :show] do
    collection do
      
      get 'search'
      post 'search'
    
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  has_one_attached :image
         
  has_many :stays
  has_many :reservations
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def  update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:image, :name, :self_introduction))
      flash[:notice] = "更新しました"
      redirect_to :edit_user
    else
    flash.now[:notice]="更新に失敗しました。もう一度入力し直してください"
      redirect_to :edit_user
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container-fiuld user">
  <div class="row-ab">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="">
          <%= link_to "アカウント",users_index_path %>
        </li>
                
        <li class="active">
          <%= link_to "プロフィール",edit_user_path(current_user.id)%>
        </li>
      </ul>
    </div>

    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="">
          <%= link_to "アカウント",users_index_path %>
        </li>
                
        <li class="active">
          <%= link_to "プロフィール",edit_user_path(current_user.id) %>
        </li>
      </ul>
    </div>

    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row-ab">
            <h5>プロフィール</h5>
          </div>
        </div>
                
        <%= form_with model: @user do |f| %>

          <div class="update-content">
            <div class="row-ab">
              <div class="col-md-6 offset-md-3" %>
                <div class="icon-box">
                  <% if @user.image.attached? %>
                    <%= image_tag @user.image,class:"icon-image host-icon"%> 
                  <% else %>
                    <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg"  alt='アイコン画像' class="icon-image host-icon">
                  <% end %>  
                </div>
              </div>
            </div>
          </div>
                
          <div class="update-content">
            <div class="row-ab">
              <%= f.label :image,"アイコン画像",class:"col-md-3 required-a" %>
              <%= f.file_field :image,class:"mb-4 col-md-9" %>
            </div>
          </div>
                
          <div class="update-content">
            <div class="row-ab">
              <%= f.label :name,"名前",class:"col-md-3 required-a" %>
              <%= f.text_field :name,placeholder:"名前を入力", class:"form-control col-md-9 mb-4" %>
            </div>
          </div>
                
          <div class="update-content">
            <div class="row-ab">
              <%= f.label :self_introduction,"自己紹介",class:"col-md-3 required-a" %>
              <%= f.text_area :self_introduction,rows:"5",placeholder:"自己紹介を入力", class:"form-control mb-4 col-md-9" %>
            </div>
          </div>
          
          <div class="update-content">
            <div class="row-ab">
              <%= f.submit "更新" ,class:"col-md-2 btn btn-primary mx-3"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container-fiuld user">
  <div class="row-ab">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to "アカウント",users_index_path %>
        </li>
        <li class="">
          <%= link_to "プロフィール",edit_user_path(current_user.id) %>
        </li>
      </ul>
    </div>

    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="active">
          <%= link_to "アカウント",users_index_path %>
        </li>
        <li class="">
          <%= link_to "プロフィール",edit_user_path(current_user.id) %>
        </li>
      </ul>
    </div>

    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row-ab">
            <h5>アカウント</h5>
          </div>
        </div>
    <%= form_with model: @user, url: user_registration_path, id: 'new_user', class: 'new_user', local: true do |f| %>
      <div class="update-content">
        <div class="row-ab">
          <%= f.label :メールアドレス,class:"col-md-3" %><br />
          <div class="col-md-9"><%= @user.email %></div>
        </div>
      </div>
                
      <div class="update-content">
        <div class="row-ab">
          <%= f.label :パスワード,class:"col-md-3" %><br />
          <div class="col-md-9">********</div>
        </div>
      </div>

      <div class="update-content"></div>
        <div class="row-ab">
          <%= link_to "編集", edit_user_registration_path,class:"col-md-2 btn btn-primary mx-3"%>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>